
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author cassandrasortais
 */
public class FenetrePrincipal extends javax.swing.JFrame {

    // Création du tableau de boutons
    private JButton[] boutons = new JButton[48];
    private int[] clicsBoutons = new int[48]; // Tableau pour suivre le nombre de clics par bouton

    /**
     * Creates new form FenetrePrincipal
     */
    public FenetrePrincipal() {
        initComponents(); // Initialise les composants créés par le GUI Builder

        // Boucle pour récupérer chaque bouton depuis le GUI Builder (btn1, btn2, ..., btn48)
        for (int i = 0; i < 48; i++) {
            // Création du nom de chaque bouton
            String nomBouton = "btn" + (i + 1); // "btn1", "btn2", ..., "btn48"

            try {
                // Utilisation de la réflexion pour obtenir chaque bouton en fonction de son nom
                boutons[i] = (JButton) this.getClass().getDeclaredField(nomBouton).get(this);
            } catch (NoSuchFieldException | IllegalAccessException e) {
                e.printStackTrace(); // Affiche l'erreur si le bouton n'est pas trouvé
            }
        }

        // Ajouter des actions aux boutons
        for (int i = 0; i < 48; i++) {
            int index = i; // Capturer l'index dans la boucle
            boutons[i].addActionListener(e -> {
                // Incrémenter le compteur de clics pour le bouton
                clicsBoutons[index]++;

                // Modifier la couleur en fonction du nombre de clics
                switch (clicsBoutons[index] % 4) {
                    case 1: // Premier clic
                        boutons[index].setBackground(Color.RED);
                        break;
                    case 2: // Deuxième clic
                        boutons[index].setBackground(Color.GREEN);
                        break;
                    case 3: // Troisième clic
                        boutons[index].setBackground(Color.YELLOW);
                        break;
                    case 0: // Quatrième clic
                        boutons[index].setBackground(Color.BLUE);
                        break;
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jTextField1.setEditable(false);
        jTextField1.setText("Code à deviner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenue dans MasterMind !");
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        jPanel1.setLayout(new java.awt.GridLayout(12, 4, 5, 5));

        btn1.setBackground(new java.awt.Color(153, 204, 255));
        btn1.setText("jButton1");
        btn1.setName("btn1"); // NOI18N
        jPanel1.add(btn1);
        btn1.getAccessibleContext().setAccessibleDescription("");

        btn2.setBackground(new java.awt.Color(153, 204, 255));
        btn2.setText("jButton2");
        jPanel1.add(btn2);

        btn3.setBackground(new java.awt.Color(153, 204, 255));
        btn3.setText("jButton3");
        jPanel1.add(btn3);

        btn4.setBackground(new java.awt.Color(153, 204, 255));
        btn4.setText("jButton4");
        jPanel1.add(btn4);

        btn5.setBackground(new java.awt.Color(153, 204, 255));
        btn5.setText("jButton5");
        jPanel1.add(btn5);

        btn6.setBackground(new java.awt.Color(153, 204, 255));
        btn6.setText("jButton6");
        jPanel1.add(btn6);

        btn7.setBackground(new java.awt.Color(153, 204, 255));
        btn7.setText("jButton7");
        jPanel1.add(btn7);

        btn8.setBackground(new java.awt.Color(153, 204, 255));
        btn8.setText("jButton8");
        jPanel1.add(btn8);

        btn9.setBackground(new java.awt.Color(153, 204, 255));
        btn9.setText("jButton9");
        jPanel1.add(btn9);

        btn10.setBackground(new java.awt.Color(153, 204, 255));
        btn10.setText("jButton10");
        jPanel1.add(btn10);

        btn11.setBackground(new java.awt.Color(153, 204, 255));
        btn11.setText("jButton11");
        jPanel1.add(btn11);

        btn12.setBackground(new java.awt.Color(153, 204, 255));
        btn12.setText("jButton12");
        jPanel1.add(btn12);

        btn13.setBackground(new java.awt.Color(153, 204, 255));
        btn13.setText("jButton13");
        jPanel1.add(btn13);

        btn14.setBackground(new java.awt.Color(153, 204, 255));
        btn14.setText("jButton14");
        jPanel1.add(btn14);

        btn15.setBackground(new java.awt.Color(153, 204, 255));
        btn15.setText("jButton15");
        jPanel1.add(btn15);

        btn16.setBackground(new java.awt.Color(153, 204, 255));
        btn16.setText("jButton16");
        jPanel1.add(btn16);

        btn17.setBackground(new java.awt.Color(153, 204, 255));
        btn17.setText("jButton17");
        jPanel1.add(btn17);

        btn18.setBackground(new java.awt.Color(153, 204, 255));
        btn18.setText("jButton18");
        jPanel1.add(btn18);

        btn19.setBackground(new java.awt.Color(153, 204, 255));
        btn19.setText("jButton19");
        jPanel1.add(btn19);

        btn20.setBackground(new java.awt.Color(153, 204, 255));
        btn20.setText("jButton20");
        jPanel1.add(btn20);

        btn21.setBackground(new java.awt.Color(153, 204, 255));
        btn21.setText("jButton21");
        jPanel1.add(btn21);

        btn22.setBackground(new java.awt.Color(153, 204, 255));
        btn22.setText("jButton22");
        jPanel1.add(btn22);

        btn23.setBackground(new java.awt.Color(153, 204, 255));
        btn23.setText("jButton23");
        jPanel1.add(btn23);

        btn24.setBackground(new java.awt.Color(153, 204, 255));
        btn24.setText("jButton24");
        jPanel1.add(btn24);

        btn25.setBackground(new java.awt.Color(153, 204, 255));
        btn25.setText("jButton25");
        jPanel1.add(btn25);

        btn26.setBackground(new java.awt.Color(153, 204, 255));
        btn26.setText("jButton26");
        jPanel1.add(btn26);

        btn27.setBackground(new java.awt.Color(153, 204, 255));
        btn27.setText("jButton27");
        jPanel1.add(btn27);

        btn28.setBackground(new java.awt.Color(153, 204, 255));
        btn28.setText("jButton28");
        jPanel1.add(btn28);

        btn29.setBackground(new java.awt.Color(153, 204, 255));
        btn29.setText("jButton29");
        jPanel1.add(btn29);

        btn30.setBackground(new java.awt.Color(153, 204, 255));
        btn30.setText("jButton30");
        jPanel1.add(btn30);

        btn31.setBackground(new java.awt.Color(153, 204, 255));
        btn31.setText("jButton31");
        jPanel1.add(btn31);

        btn32.setBackground(new java.awt.Color(153, 204, 255));
        btn32.setText("jButton32");
        jPanel1.add(btn32);

        btn33.setBackground(new java.awt.Color(153, 204, 255));
        btn33.setText("jButton33");
        jPanel1.add(btn33);

        btn34.setBackground(new java.awt.Color(153, 204, 255));
        btn34.setText("jButton34");
        jPanel1.add(btn34);

        btn35.setBackground(new java.awt.Color(153, 204, 255));
        btn35.setText("jButton35");
        jPanel1.add(btn35);

        btn36.setBackground(new java.awt.Color(153, 204, 255));
        btn36.setText("jButton36");
        jPanel1.add(btn36);

        btn37.setBackground(new java.awt.Color(153, 204, 255));
        btn37.setText("jButton37");
        jPanel1.add(btn37);

        btn38.setBackground(new java.awt.Color(153, 204, 255));
        btn38.setText("jButton38");
        jPanel1.add(btn38);

        btn39.setBackground(new java.awt.Color(153, 204, 255));
        btn39.setText("jButton39");
        jPanel1.add(btn39);

        btn40.setBackground(new java.awt.Color(153, 204, 255));
        btn40.setText("jButton40");
        btn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn40ActionPerformed(evt);
            }
        });
        jPanel1.add(btn40);

        btn41.setBackground(new java.awt.Color(153, 204, 255));
        btn41.setText("jButton41");
        jPanel1.add(btn41);

        btn42.setBackground(new java.awt.Color(153, 204, 255));
        btn42.setText("jButton42");
        jPanel1.add(btn42);

        btn43.setBackground(new java.awt.Color(153, 204, 255));
        btn43.setText("jButton43");
        jPanel1.add(btn43);

        btn44.setBackground(new java.awt.Color(153, 204, 255));
        btn44.setText("jButton44");
        jPanel1.add(btn44);

        btn45.setBackground(new java.awt.Color(153, 204, 255));
        btn45.setText("jButton45");
        jPanel1.add(btn45);

        btn46.setBackground(new java.awt.Color(153, 204, 255));
        btn46.setText("jButton46");
        jPanel1.add(btn46);

        btn47.setBackground(new java.awt.Color(153, 204, 255));
        btn47.setText("jButton47");
        jPanel1.add(btn47);

        btn48.setBackground(new java.awt.Color(153, 204, 255));
        btn48.setText("jButton48");
        jPanel1.add(btn48);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn40ActionPerformed
        FenetrePrincipal.super.dispose();
        Menu men3 = new Menu ();
        men3.setVisible(true);
       
    }//GEN-LAST:event_btn40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
